### ISSUE TITLE
Respect name changes

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/fullname#13]
I am making [first-name](https://github.com/sholladay/first-name), which is built on top of this module.

Writing good tests for it is difficult because `fullname` caches the result. I could maybe use [this trick](https://github.com/sindresorhus/fullname/blob/b32c3c1e19c3e0b492d98885ec2c7fba8d5106c0/test.js#L29) but it seems ugly to do that to a dependency. And if I ever have to write a module on top of `first-name` where trying out different names is useful, then _that modules's tests_ may not be able to do so because you can't always require a sub-dependency, depending on how `npm` structures the tree.

Any thoughts on approaches to deal with this?

More broadly, the memoization here is strange because `fullname` doesn't take any input. Thus it has no way to know when the computation should be performed again, which is a core tenet of memoization. And even though it may not be common, the user's name certainly can change.

My solutions:

1. `fullname.noCache()` does the same work, bypassing the cache.
2. `fullname()` implements a lazily updated cache. So it would have a shortcut to resolve quickly with a cached value if one is available, but would trigger a non-blocking background update of the cache so that future calls can return a more up-to-date value.
3. We leave everything as-is but use `mem`'s [`cacheKey`](https://github.com/sindresorhus/mem#cachekey) feature to cache based on relevant properties from `process.env`. So changes to the environment can be returned immediately. However, unlike `2`, in the event that no environment variables are defined, the module keeps behaving as it does now (i.e. you are "stuck" with a name permanently).

My favorite is `3`, and it would look something like this:

```js
module.exports = mem(getFullName, {
    cacheKey(input) {
        return JSON.stringify(filterObj(process.env, [
            'GIT_AUTHOR_NAME',
            'GIT_COMMITTER_NAME'
            // ...
        ]));
    }
});
```

**Comment by sindresorhus** [comment]
The thinking is that realistically the user never changes their name, and even if they do, we can have it stale until the next run. Some of the calls are very expensive (especially the Windows one), so it's something you want to do too often. I'm ok with `3`.
