### ISSUE TITLE
Russian letters seem to cause the method to return object instead of a string

### ISSUE THREAD

**Issue by mischah** [sindresorhus/fullname#15]
Hej, 

sorry that this issue is kind of vague. @vitalkanev reported the issue in the yo repo over here: yeoman/yo#540.

I wasn’t able reproduce the issue with this username with Mac OS 10.12.6:

    шуталы Phillipow

So it might be a linux specific issue?!?

**Comment by sindresorhus** [comment]
What does the object contain?
