### ISSUE TITLE
checkWmic function returns '\r\r\n\r' without user information

### ISSUE THREAD

**Issue by pktippa** [sindresorhus/fullname#16]
When I run individually from command prompt it gives a valid response.

```batch
C:\Users\Pradeep_Tippa>wmic useraccount where name="%username%" get fullname
FullName
Pradeep Kumar Tippa
```

Where as when i use checkWmic code it is failing.

```batch
C:\Users\Pradeep_Tippa>node sample.js
Stdout

```

We are using [fullname().then(name)](https://github.com/EdgeVerve/oe-starter-app/blob/master/app/index.js#L7) in our [cli starter-app](https://github.com/edgeverve/oe-starter-app)

Please help. Let me know if you need more information.

**Comment by sindresorhus** [comment]
// @MarkTiedemann I'm trying my luck here too, in case you'd like to make a binary to get the fullname 🙏

You could borrow the logic from https://github.com/sindresorhus/fullname-native/blob/85684089a22698e6d7f1c629da7eee268960ba17/binding.cc#L28-L34

**Comment by MarkTiedemann** [comment]
@sindresorhus Done, see: [`fullname`](https://github.com/MarkTiedemann/fullname).

**Comment by rameshvarun** [comment]
I think the issue is that `%username%` isn't being properly replaced unless you add a `{ shell: true }` argument - see #18.
