### ISSUE TITLE
What is the script to fallback username when fullname isn't found?

### ISSUE THREAD

**Issue by DaniellMesquita** [sindresorhus/fullname#20]
@sindresorhus

**Comment by sindresorhus** [comment]
It's documented in the readme.

**Comment by DaniellMesquita** [comment]
> In the rare case a name can't be found, you could fall back to username.

No, in the code, there is no mention to username package.

**Comment by DaniellMesquita** [comment]
> you could fall back to username.

"you could" means user could do it yourself, not meaning it already does fallback.
