### ISSUE TITLE
The subprocess to get fullname not work in Ubuntu when user is a local user, but authenticated from Ldap

### ISSUE THREAD

**Issue by abner** [sindresorhus/fullname#4]
I suggest this fallback
 grep "^`whoami`:" /etc/passwd | awk -F: '{print $5}'

**Comment by sindresorhus** [comment]
"Does not work" isn't very helpful. So you get no output? If you look at the food you'll see that it has multiple fallbacks. I'm surprised none of those work.

What do you get when running:

```
$ getent passwd $(whoami)
```

and 

```
$ git config --global user.name
```

**Comment by abner** [comment]
i'm just getting an error:
node_modules/fullname/index.js:84
		fullname = stdout.trim().split(':')[4].replace(/,.*/, '');
		                                      ^
TypeError: Cannot read property 'replace' of undefined

**Comment by sindresorhus** [comment]
Please read my comment again and answer everything I asked.

**Comment by abner** [comment]
The command getent passwd $(whoami) in my environment returns a empty string.
The fallback   git config --global user.name  is not executed because of the error at line 84
node_modules/fullname/index.js:84
fullname = stdout.trim().split(':')[4].replace(/,.*/, '');

The error is raised because of the replace function called upon undefined. split(":") on a empty string returns an array with only one position, so [4] returns undefined, and then, replace call raises the error.

**Comment by sindresorhus** [comment]
Alright. That's helpful. Fixed in 1.1.1 ;)

**Comment by abner** [comment]
You're welcome

**Comment by abner** [comment]
Just for information, this bug was affecting yeoman, which uses fullname. I just forgot to say that.
